import React from "react";

import Head from 'next/head'
import Image from "next/image";

import styles from '../styles/Home.module.css'

import background from "../assets/wallpaper.jpg";
import Navbar from '../components/navbar/Navbar';


export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="fixed h-screen flex z-1">
                <Image src={background}  alt=""/>
            </div>
            <div className="absolute z-10 top-[2%] left-[2%]">
                <div className="flex justify-center items-center">
                    <Navbar />
                </div>
            </div>
        </div>
    )
}
